### ISSUE TITLE
small issue with your algorithm 

### ISSUE THREAD

**Issue by FrankOcean11** [Paul-Ver/OpenRoboticArm#1]
i try to run that sketch and i get this msg "Unrecognized type:46 (ENUM_DEF)" and above that it says it cant find anything named surface

what is the meaning of that msg? how can i fix it ? 
![image](https://cloud.githubusercontent.com/assets/10504709/12308526/a83e69b4-ba13-11e5-8a51-6fc795f15a62.png)

so i comment it out and then i got a new one 
![image](https://cloud.githubusercontent.com/assets/10504709/12308581/ec11eee0-ba13-11e5-86f3-98174b35398d.png)

at this point im lost, great work please help

**Comment by Paul-Ver** [comment]
You're running Processing 2.2.1, I'm running Processing 3.0.1.
There are some small changes between these versions.

You have to change: 
"surface.setTitle("blabla");" 
"surface.setResizable(true);"

to: 
"frame.setTitle("blabla");"
"frame.setResizable(true);"

Or download processing 3.0.1.

**Comment by Paul-Ver** [comment]
Also, Processing 2.2.1 does not support ENUMS.
I've changed the enums to chars, should work fine now.
Though, you might still want to upgrade to Processing 3.0.1 ;)

Paul-Ver Fixed some compatiblity issues with processing 2.2.1 …
Issue: small issue with your algorithm #1
Status: should be resolved.

**Comment by Paul-Ver** [comment]
Let me know if it works for you :)

**Comment by FrankOcean11** [comment]
what about this class ? 
![image](https://cloud.githubusercontent.com/assets/10504709/12364931/9dadfc70-bb9f-11e5-8612-6b2de321a6de.png)

and thanks

**Comment by Paul-Ver** [comment]
The "Unrecognized type:46 (ENUM_DEF)" error would be caused by the rotationAxis enum.
The rotationAxis enum would indicate which way the part of the arm would turn when rotating it.

In the new version (https://github.com/Paul-Ver/RoboticsSimulation/commit/34217c0e6c22a8e7d2656669c6cbaa675726db30)
I have changed it to a char. 'x', 'y', 'z' or 'n' for none instead of using enums.

Thus, the new version should be working.
I also tested it in Processing 2.2.1, so I believe you're good to go.
If it works, please leave a comment, so I can resolve this issue :)

:+1:

**Comment by FrankOcean11** [comment]
yes it is working i just downloaded the new one rather then editing the old one, thank, im trying to change the controls cuz im not finding using keys too friendly , im looking for a way to map the mouse hover to those of the keyboard instead,

as far as functionality is this supposed to work with Arduino ? cuz i have a arm i like to control thru this ide gui  you made here 

also im trying to add collision avoidance/contains for the floor cuz the arm seem to want to go pass the floor for some reason and the red ball also is being allowed to go pass the floor and its boundaries out of reach 


maybe this sketch will help your modification ? 

///////////////////////////////////////////////////////

int nLinks = 3;
int nGripperAngles = 5;
int GripperAngle[] = {
  0, -45, -90, 45, 90
};
int linkStrokeW[] = {
  28, 18, 12
};
int linkColor[] = {
  #00D000, #0000FF, #FF0000
};
int l[] = {
  0, 100, 100, 60
};
int h0 = 180; //Arm Origen in Screen Coordinates
int v0 = 360; //Arm Origen in Screen Coordinates
int currGripper = 0;

float[] w = new float[nLinks]; //horizontal coordinate, corresponds to P0, P1, P2 etc
float[] z = new float[nLinks]; //vertical coordinate
float[] a = new float[nLinks];  //angle for the link, reference is previous link
float tw, tz; //target coordinate for the actuator (gripper)
float tw0, tz0; //Previous target coordinate for the actuator (gripper) that was inside the robot reach
float l12;
float a12;

void setup() {
  size(480, 560); //drawing window size
  smooth(); 
  w[0] = 0;  // Set Origen
  z[0] = 0;  // Set Origen
  tw0=100; // Initiakl Target
  tz0=100;
}

void draw() {
  background(240);
  checkMouseInMenu(mouseX, mouseY);
  drawGripperMenu();
  drawAxes();
  tw = mouseX - h0;
  tz = v0 - mouseY ;
  calcP2();
  if (l12>l[1]+l[2]) {
    textAlign(CENTER); 
    fill(#FF0000);
    text("No Solution", 240, 70);
    text("Move mouse pointer towards the origin.", 240, 84);
    tw=tw0;
    tz=tz0;
    calcP2();
  }
  calcP1();
  drawLinks();
  tw0=tw;
  tz0=tz;
}

void drawAxes() {
  strokeWeight(1);
  stroke(0);
  line(h0, v0, h0+259, v0);
  line(h0, v0, h0, v0-259);
}

void checkMouseInMenu(float hin, float vin) {
  int H = 120;
  if ((vin>436) && (vin<454)) { 
    for (int i=0; i<nGripperAngles; i++) {  
      if ((hin>H-20) && (hin<H+20)) {
        currGripper=i;
      }
      H=H+44;
    }
  }
}

void drawGripperMenu() {
  textAlign(CENTER);
  text("Robot Arm Inverse Kinematics Algorithm Simulation", 240, 40);
  int H = 60;
  int V = 424;
  fill(0);
  textAlign(LEFT);  
  text("To change gripper angle roll mouse over new value", H, V);
  textAlign(CENTER);
  H = 120;
  V = 450;
  for (int i=0; i<nGripperAngles; i++) {  
    if (i == currGripper) {
      fill(0);
    } else {
      fill(180);
    }
    text(GripperAngle[i], H, V);
    H = H+44;
  }
}

void calcP2() {
  w[2]=tw-cos(radians(GripperAngle[currGripper]))*l[3];
  z[2]=tz-sin(radians(GripperAngle[currGripper]))*l[3];
  l12 = sqrt(sq(w[2])+sq(z[2]));
}

void calcP1() {
  a12=atan2(z[2], w[2]);
  a[1]=acos((sq(l[1])+sq(l12)-sq(l[2]))/(2*l[1]*l12))+a12;
  w[1]=cos(a[1])*l[1];
  z[1]=sin(a[1])*l[1];
}

void drawLinks() {
  for (int i=0; i<2; i++) {  
    strokeWeight(linkStrokeW[i]);
    stroke(linkColor[i]);
    line(h0+w[i], v0-z[i], h0+w[i+1], v0-z[i+1]);
  }
  strokeWeight(linkStrokeW[2]);
  stroke(linkColor[2]);
  line(h0+w[2], v0-z[2], h0+ tw, v0- tz);
  fill(0);
  strokeWeight(0);
  stroke(0);
  ellipse(h0+ tw, v0- tz, 10, 10);
}

**Comment by Paul-Ver** [comment]
What type of robotic arm do you have?
Or what code is on the side of arduino, I was thinking of adding support for arduino robotic arms.

But, I currently only have 2 to 3 servo's on my robotic arm, so I have to buy some more, to represent all joints.
But if you can link me to the protocol for your robotic arm, or assist me in creating a protocol.

Mouse control is a good idea, though it should be compatible with the current world rotation (mouse dragging) plus, the arm can move in 3D, mouse is usually only 2D.

**Comment by Paul-Ver** [comment]
I've added some basic mouse-controls.

Also, I've added a function to send info over a COM-port, to communicate with arduino.
But, for this I need a specification on the arduino-arm protocol.
So which type of arm do you have/want to control, or how should I send the values to arduino?

We're going to need a protocol like:
@1#SetAngles(90,0,20,10,90)\r or something.
use @ for the identification, #command for the command, like: SetAngles, SetMoveSpeed, SetGripper? But you could check if you're working with a robotic arm that already has a protocol specified.

**Comment by FrankOcean11** [comment]
whats your email?

**Comment by FrankOcean11** [comment]
CTRL + mouseDragged = 3D WorldCoordinate 
crtl == coordinate Z
mouseDragged == coordinate X&Y

this is solving the usual 2D issue and now we can move in 3D Space

**Comment by FrankOcean11** [comment]
2D to 3D conversion 
rotate on Z by holding CTRL + mouseDrag
release CTRL and back to mouseDrag on X&Y coordinate 

you ask for what type of arm i have for arduino-
![image](https://cloud.githubusercontent.com/assets/10504709/12380823/e01890f6-bd49-11e5-87bd-9b0b9abc3936.png)

wrist, elbow and shoulder are part of this arm revolute joints the DOF is that of any human so those are pretty arbitrary 

if you can pass me your email we can work on the protocol as my protocol for my arm is pretty large and by the architecture of my design it is not common to anyone but me unless i release the the CAD source and someone prints the assembly but more on that in private.

**Comment by FrankOcean11** [comment]
you can always use ctrl on your keyboard to rotate on a hovering over a particular joint and be able to move on its confined dof

**Comment by Paul-Ver** [comment]
Hmm, I don't really think the controls have to be adjusted.
WASD(QE) controls are pretty straightforward.
Or, at least it has no priority at this moment.

Anyone can try if he wants, if you do, consider sending in a pull request.

I'll be focussing on getting the hardware prototype done, if that's down (and I get annoyed by the controls) I might check one of they options you propose.
